# Generated by Django 4.1 on 2024-08-22 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sucursales", "0001_initial"),
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_documento", models.CharField(max_length=20, unique=True)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("NOTA", "Nota de Venta"), ("FACTURA", "Factura")],
                        max_length=7,
                    ),
                ),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                (
                    "monto_total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "cliente_nombre",
                    models.CharField(
                        blank=True,
                        default="Consumidor Final",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "cliente_ci_ruc",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                (
                    "cliente_direccion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ventas", models.ManyToManyField(to="ventas.venta")),
            ],
        ),
        migrations.CreateModel(
            name="CierreCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "efectivo_total",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tarjeta_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transferencia_total",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "salidas_caja",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("fecha_cierre", models.DateTimeField(auto_now_add=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sucursales.sucursal",
                    ),
                ),
            ],
        ),
    ]
