# Generated by Django 4.1 on 2024-08-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0002_notaventa_cierrecaja"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notaventa",
            name="ventas",
        ),
        migrations.AlterField(
            model_name="notaventa",
            name="monto_total",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
        ),
    ]
