# Generated by Django 5.1.1 on 2024-10-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0002_carrito_presentacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="cierrecaja",
            name="motivo_salida",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
