# Generated by Django 4.1 on 2024-08-29 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0004_registroturno"),
        ("ventas", "0003_remove_notaventa_ventas_alter_notaventa_monto_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="turno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ventas",
                to="empleados.registroturno",
            ),
        ),
    ]
