# Generated by Django 4.1 on 2024-08-29 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0004_registroturno"),
        ("ventas", "0004_venta_turno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="turno",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ventas",
                to="empleados.registroturno",
            ),
            preserve_default=False,
        ),
    ]
