# Generated by Django 4.1 on 2024-08-31 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0006_carrito"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NotaVenta",
        ),
    ]
