# Generated by Django 4.1 on 2024-09-07 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0007_delete_notaventa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="metodo_pago",
        ),
    ]
