# Generated by Django 4.1 on 2024-09-13 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0015_factura_registroturno"),
        ("ventas", "0008_remove_venta_metodo_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="factura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ventas",
                to="facturacion.factura",
            ),
        ),
    ]
