# Generated by Django 4.1 on 2024-09-14 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0015_factura_registroturno"),
        ("ventas", "0009_venta_factura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="factura",
            field=models.ForeignKey(
                default=18,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ventas",
                to="facturacion.factura",
            ),
            preserve_default=False,
        ),
    ]
