# Generated by Django 4.1 on 2024-09-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0007_remove_registroturno_facturas"),
        ("ventas", "0010_alter_venta_factura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cierrecaja",
            name="empleado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="empleados.empleado"
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="empleado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="empleados.empleado",
            ),
        ),
    ]
