# Generated by Django 4.1 on 2024-09-29 21:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                ("razon_social", models.CharField(max_length=200, unique=True)),
                (
                    "ruc",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El RUC debe tener exactamente 13 dígitos numéricos.",
                                regex="^\\d{13}$",
                            )
                        ],
                    ),
                ),
                ("direccion", models.TextField()),
                ("telefono", models.CharField(max_length=20)),
                (
                    "codigo_establecimiento",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "punto_emision",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("es_matriz", models.BooleanField(default=False)),
                (
                    "secuencial_actual",
                    models.CharField(default="000000001", max_length=9),
                ),
                (
                    "usuarios",
                    models.ManyToManyField(
                        related_name="sucursales", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "unique_together": {("codigo_establecimiento", "punto_emision")},
            },
        ),
    ]
