# Generated by Django 4.1 on 2024-08-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sucursal",
            name="codigo_establecimiento",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="sucursal",
            name="punto_emision",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="sucursal",
            name="razon_social",
            field=models.CharField(default="Empresa Desconocida", max_length=200),
        ),
        migrations.AddField(
            model_name="sucursal",
            name="ruc",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name="sucursal",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
    ]
