# Generated by Django 4.1 on 2024-09-05 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursales", "0003_alter_sucursal_codigo_establecimiento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sucursal",
            name="secuencial_actual",
            field=models.CharField(default="000000001", max_length=9),
        ),
        migrations.AlterField(
            model_name="sucursal",
            name="codigo_establecimiento",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="sucursal",
            name="punto_emision",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="sucursal",
            name="ruc",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El RUC debe tener exactamente 13 dígitos numéricos.",
                        regex="^\\d{13}$",
                    )
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sucursal",
            unique_together={("codigo_establecimiento", "punto_emision")},
        ),
    ]
