# Generated by Django 4.1 on 2024-09-02 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empleados", "0004_registroturno"),
        ("sucursales", "0003_alter_sucursal_codigo_establecimiento_and_more"),
        ("inventarios", "0006_compra_precio_unitario_alter_compra_sucursal_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identificacion", models.CharField(max_length=13, unique=True)),
                (
                    "tipo_identificacion",
                    models.CharField(
                        choices=[
                            ("04", "RUC"),
                            ("05", "Cédula"),
                            ("06", "Pasaporte"),
                            ("07", "Consumidor Final"),
                        ],
                        max_length=2,
                    ),
                ),
                ("razon_social", models.CharField(max_length=200)),
                ("direccion", models.CharField(blank=True, max_length=300, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                (
                    "numero_autorizacion",
                    models.CharField(blank=True, max_length=49, null=True, unique=True),
                ),
                (
                    "clave_acceso",
                    models.CharField(blank=True, max_length=49, null=True, unique=True),
                ),
                (
                    "total_sin_impuestos",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_con_impuestos",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("EN_PROCESO", "En Proceso"),
                            ("AUTORIZADA", "Autorizada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="EN_PROCESO",
                        max_length=20,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facturacion.cliente",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="empleados.empleado",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sucursales.sucursal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Impuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("porcentaje", models.DecimalField(decimal_places=2, max_digits=5)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forma_pago", models.CharField(max_length=50)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_pago", models.DateTimeField(auto_now_add=True)),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="facturacion.factura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacturaImpuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_imponible",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impuestos",
                        to="facturacion.factura",
                    ),
                ),
                (
                    "impuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facturacion.impuesto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleFactura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="facturacion.factura",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventarios.producto",
                    ),
                ),
            ],
        ),
    ]
