# Generated by Django 4.1 on 2024-09-29 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sucursales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventarios", "0001_initial"),
        ("facturacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallefactura",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventarios.producto"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="facturacion.cliente",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sucursales.sucursal"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="factura",
            unique_together={("sucursal", "numero_autorizacion")},
        ),
    ]
