# Generated by Django 4.1 on 2024-09-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="numero_autorizacion",
            field=models.CharField(max_length=49, unique=True),
        ),
    ]
