# Generated by Django 4.1 on 2024-09-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0003_comprobantepago"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="contribuyente_especial",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="factura",
            name="moneda",
            field=models.CharField(default="DOLAR", max_length=10),
        ),
        migrations.AddField(
            model_name="factura",
            name="obligado_contabilidad",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="factura",
            name="tipo_comprobante",
            field=models.CharField(
                choices=[("01", "Factura")], default="01", max_length=2
            ),
        ),
    ]
