# Generated by Django 5.1.1 on 2024-10-09 09:55

import facturacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_factura_numero_autorizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to=facturacion.models.ruta_factura),
        ),
    ]
