# Generated by Django 5.1.1 on 2024-10-11 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0004_factura_archivo_pdf"),
        ("inventarios", "0007_alter_inventario_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallefactura",
            name="presentacion",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventarios.presentacion",
            ),
            preserve_default=False,
        ),
    ]
