# Generated by Django 4.1 on 2024-09-05 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0004_factura_contribuyente_especial_factura_moneda_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="obligado_contabilidad",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="identificacion",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="La identificación debe tener 10 dígitos (cédula) o 13 dígitos (RUC).",
                        regex="^\\d{10}|\\d{13}$",
                    )
                ],
            ),
        ),
    ]
