# Generated by Django 4.1 on 2024-09-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0005_cliente_obligado_contabilidad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallefactura",
            name="codigo_principal",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
