# Generated by Django 5.1.1 on 2024-10-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0005_detallefactura_presentacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="es_cotizacion",
            field=models.BooleanField(default=False),
        ),
    ]
