# Generated by Django 4.1 on 2024-09-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0006_detallefactura_codigo_principal"),
    ]

    operations = [
        migrations.AddField(
            model_name="impuesto",
            name="codigo_impuesto",
            field=models.CharField(default=2, max_length=2),
            preserve_default=False,
        ),
    ]
