# Generated by Django 5.1.1 on 2024-10-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_factura_es_cotizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='es_cotizacion',
        ),
    ]
