# Generated by Django 5.1.1 on 2024-10-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_remove_factura_es_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='es_cotizacion',
            field=models.BooleanField(default=False),
        ),
    ]
