# Generated by Django 4.1 on 2024-09-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0008_factura_estado_pago_alter_factura_tipo_comprobante"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pago",
            name="forma_pago",
        ),
        migrations.RemoveField(
            model_name="pago",
            name="valor",
        ),
        migrations.AddField(
            model_name="pago",
            name="codigo_sri",
            field=models.CharField(
                choices=[
                    ("01", "Sin utilización del sistema financiero"),
                    ("15", "Compensación de deudas"),
                    ("16", "Tarjeta de débito"),
                    ("17", "Dinero electrónico"),
                    ("18", "Tarjeta prepago"),
                    ("19", "Tarjeta de crédito"),
                    ("20", "Otros con utilización del sistema financiero"),
                    ("21", "Endoso de títulos"),
                ],
                default="01",
                help_text="Código del método de pago según el SRI",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="descripcion",
            field=models.CharField(
                default="Sin descripción",
                help_text="Descripción del método de pago",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="plazo",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Plazo de pago en días, si aplica",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Monto total del pago",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="unidad_tiempo",
            field=models.CharField(
                blank=True,
                default="días",
                help_text="Unidad de tiempo para el plazo, ej. días, meses",
                max_length=20,
                null=True,
            ),
        ),
    ]
