# Generated by Django 4.1 on 2024-09-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0009_remove_pago_forma_pago_remove_pago_valor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="impuesto",
            name="monto",
        ),
        migrations.AddField(
            model_name="impuesto",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
