# Generated by Django 4.1 on 2024-09-07 06:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0011_factura_valor_iva"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallefactura",
            name="valor_iva",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
