# Generated by Django 4.1 on 2024-09-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0012_detallefactura_valor_iva"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="numero_autorizacion",
            field=models.CharField(default=0, max_length=49),
            preserve_default=False,
        ),
    ]
