# Generated by Django 4.1 on 2024-09-12 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sucursales", "0004_sucursal_secuencial_actual_and_more"),
        ("facturacion", "0013_alter_factura_numero_autorizacion"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="factura",
            unique_together={("sucursal", "numero_autorizacion")},
        ),
    ]
