# Generated by Django 4.1 on 2024-08-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="grupo",
            field=models.CharField(
                choices=[("Empleado", "Empleado"), ("Administrador", "Administrador")],
                default="Empleado",
                max_length=20,
            ),
        ),
    ]
