# Generated by Django 4.1 on 2024-08-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursales", "0001_initial"),
        ("empleados", "0002_empleado_grupo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empleado",
            name="sucursal",
        ),
        migrations.AddField(
            model_name="empleado",
            name="sucursales",
            field=models.ManyToManyField(blank=True, to="sucursales.sucursal"),
        ),
    ]
