# Generated by Django 4.1 on 2024-09-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0004_registroturno"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroturno",
            name="otros_metodos_pago",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="registroturno",
            name="total_efectivo",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="registroturno",
            name="total_ventas",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
