# Generated by Django 4.1 on 2024-09-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0013_alter_factura_numero_autorizacion"),
        ("empleados", "0005_registroturno_otros_metodos_pago_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroturno",
            name="facturas",
            field=models.ManyToManyField(blank=True, to="facturacion.factura"),
        ),
    ]
