# Generated by Django 4.1 on 2024-09-12 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0006_registroturno_facturas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registroturno",
            name="facturas",
        ),
    ]
