# Generated by Django 4.1 on 2024-09-13 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sucursales", "0004_sucursal_secuencial_actual_and_more"),
        ("empleados", "0007_remove_registroturno_facturas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_ventas",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("total_facturas", models.IntegerField(default=0)),
                (
                    "total_efectivo",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "otros_metodos_pago",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("fecha", models.DateField()),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sucursales.sucursal",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes",
                        to="empleados.registroturno",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha"],
            },
        ),
    ]
