# Generated by Django 4.1 on 2024-08-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventarios", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="precio",
            new_name="precio_compra",
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_venta",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
