# Generated by Django 5.1.1 on 2024-09-30 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0003_alter_factura_numero_autorizacion"),
        ("inventarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="impuesto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="facturacion.impuesto",
            ),
        ),
    ]
