# Generated by Django 5.1.1 on 2024-10-10 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventarios", "0002_alter_producto_impuesto"),
        ("sucursales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Presentacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_presentacion", models.CharField(max_length=50)),
                ("cantidad", models.PositiveIntegerField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presentaciones",
                        to="inventarios.producto",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presentaciones",
                        to="sucursales.sucursal",
                    ),
                ),
            ],
        ),
    ]
