# Generated by Django 4.1 on 2024-08-22 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sucursales", "0001_initial"),
        ("inventarios", "0002_rename_precio_producto_precio_compra_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventario",
            name="cantidad",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="inventario",
            unique_together={("producto", "sucursal")},
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("COMPRA", "Compra"),
                            ("TRANSFERENCIA_ENTRADA", "Transferencia Entrada"),
                            ("TRANSFERENCIA_SALIDA", "Transferencia Salida"),
                            ("VENTA", "Venta"),
                        ],
                        max_length=25,
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventarios.producto",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sucursales.sucursal",
                    ),
                ),
            ],
        ),
    ]
