# Generated by Django 5.1.1 on 2024-10-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventarios", "0003_presentacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="precio_venta",
        ),
    ]
