# Generated by Django 5.1.1 on 2024-10-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventarios", "0004_remove_producto_precio_venta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="precio_compra",
        ),
    ]
