# Generated by Django 4.1 on 2024-08-26 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sucursales", "0001_initial"),
        ("inventarios", "0004_categoria_producto_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sucursales.sucursal",
            ),
        ),
    ]
