# Generated by Django 5.1.1 on 2024-10-10 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventarios", "0005_remove_producto_precio_compra"),
        ("sucursales", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventario",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="inventario",
            name="presentacion",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventarios",
                to="inventarios.presentacion",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="inventario",
            unique_together={("presentacion", "sucursal")},
        ),
    ]
