# Generated by Django 4.1 on 2024-08-28 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sucursales", "0001_initial"),
        ("inventarios", "0005_producto_sucursal"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="precio_unitario",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sucursales.sucursal"
            ),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="cantidad",
            field=models.IntegerField(),
        ),
    ]
