# Generated by Django 4.1 on 2024-09-02 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0001_initial"),
        ("inventarios", "0006_compra_precio_unitario_alter_compra_sucursal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="codigo_producto",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="impuesto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="facturacion.impuesto",
            ),
        ),
    ]
