# Generated by Django 5.1.1 on 2024-10-10 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventarios", "0006_alter_inventario_unique_together_and_more"),
        ("sucursales", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventario",
            unique_together={("producto", "sucursal")},
        ),
        migrations.RemoveField(
            model_name="inventario",
            name="presentacion",
        ),
    ]
