# Generated by Django 4.1 on 2024-09-06 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventarios", "0007_producto_codigo_producto_producto_impuesto"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 9, 6, 3, 21, 36, 334547, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="producto",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
        migrations.AddField(
            model_name="producto",
            name="stock_minimo",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="producto",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
