# Generated by Django 5.1.1 on 2024-10-11 14:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventarios", "0007_alter_inventario_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("ruc", models.CharField(max_length=13)),
                ("direccion", models.CharField(max_length=255)),
                ("telefono", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="compra",
            name="cantidad",
        ),
        migrations.RemoveField(
            model_name="compra",
            name="fecha",
        ),
        migrations.RemoveField(
            model_name="compra",
            name="precio_unitario",
        ),
        migrations.RemoveField(
            model_name="compra",
            name="producto",
        ),
        migrations.AddField(
            model_name="compra",
            name="estado",
            field=models.CharField(
                choices=[
                    ("completada", "Completada"),
                    ("pendiente", "Pendiente"),
                    ("cancelada", "Cancelada"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="compra",
            name="fecha_emision",
            field=models.DateField(
                default=datetime.datetime(2024, 10, 11, 14, 1, 16, 491553)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="compra",
            name="metodo_pago",
            field=models.CharField(
                choices=[("efectivo", "Efectivo"), ("transferencia", "Transferencia")],
                default="efectivo",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="compra",
            name="numero_autorizacion",
            field=models.CharField(default="0000000000", max_length=50),
        ),
        migrations.AddField(
            model_name="compra",
            name="total_con_impuestos",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="compra",
            name="total_descuento",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="compra",
            name="total_sin_impuestos",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="DetalleCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_principal", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=255)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_por_producto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "impuesto_aplicado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "valor_impuesto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="inventarios.compra",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventarios.producto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="compra",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventarios.proveedor",
            ),
        ),
    ]
