# Generated by Django 4.1 on 2024-09-06 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sucursales", "0004_sucursal_secuencial_actual_and_more"),
        (
            "inventarios",
            "0008_producto_activo_producto_created_at_producto_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferencia",
            name="sucursal_origen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transferencias_salida",
                to="sucursales.sucursal",
            ),
        ),
    ]
