# Generated by Django 5.1.1 on 2024-10-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventarios",
            "0008_proveedor_remove_compra_cantidad_remove_compra_fecha_and_more",
        ),
        ("sucursales", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="sucursal",
        ),
        migrations.AddField(
            model_name="producto",
            name="sucursales",
            field=models.ManyToManyField(blank=True, to="sucursales.sucursal"),
        ),
    ]
